### ISSUE TITLE
The Future of BoofCPP, and QR Code Detection

### ISSUE THREAD

**Issue by delta42** [lessthanoptimal/BoofCPP#1]
Hello,
    I was wondering if BoofCPP will be worked on in the future, and more specifically, my interest is being able to benchmark QR Code Detection as described here:

https://boofcv.org/index.php?title=Example_Detect_QR_Code

My environment only allows me to work in C++.
Thanks in advance.

**Comment by lessthanoptimal** [comment]
The C++ port was only really intended to be a port of the most speed critical parts of different components in BoofCV. It has stalled actually because the speed up wasn't all that great even after a couple rounds of optimization. Trivial algorithms got much faster, but those weren't the critical ones. Slightly more complex algorithms produced comparable results to Java.

I've used memory mapped files to make communication between Java and C++ very fast in the past.

**Comment by delta42** [comment]
Thanks for the heads up. Unfortunately in the context my code is running in I can't include the Java runtime.
I'm having difficulty reading skewed and rotated QR codes. But I will solve this another way...

Thanks again.
